# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6411b82b598370d863124420c7c8666f"
name = "Rewardly"
application_url = "https://globally-new-cougar.ngrok-free.app/"
embedded = true

[build]
dev_store_url = "function-discount-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://globally-new-cougar.ngrok-free.app/auth/callback",
  "https://globally-new-cougar.ngrok-free.app/auth/shopify/callback"
]

[webhooks]
api_version = "2023-10"

[app_proxy]
url = "https://aphid-learning-evenly.ngrok-free.app/"
subpath = "bundle-host"
prefix = "apps"

[pos]
embedded = false
